// MultibodyImportTests.swift
// OCCTSwiftCADKitTests
//
// Cover for a real multibody import, which this package could not exercise until #13: both
// camera-framing regressions (OCCTSwiftUX#12 / OCCTSwiftCADKit#19) had to assert the bounds union
// directly, because no multi-body file existed to drive the path end to end.
//
// The fixture is `Fixtures/multibody-three-solids.brep`, generated by the OCCTSwiftScripts script
// committed alongside it. Three solids, deliberately far apart and differently sized:
//
//   asm-0   4x4x4 box    x  -2 ..  2
//   asm-1   cylinder     x  27 .. 33
//   asm-2   6x6x6 box    x  57 .. 63
//
// The separation is the point. Framing the first body alone spans 4mm; framing all three spans
// 65mm. An assertion about the union therefore cannot be satisfied by a camera that frames only
// body 0, which is exactly the bug these tests exist for.

import Foundation
import OCCTSwift
import Testing

@testable import OCCTSwiftCADKit

@Suite struct MultibodyImportTests {

    private static func fixtureURL() throws -> URL {
        try #require(
            Bundle.module.url(
                forResource: "multibody-three-solids", withExtension: "brep",
                subdirectory: "Fixtures"),
            "the multibody fixture must be bundled; check resources: [.copy(\"Fixtures\")]")
    }

    @MainActor
    @Test("A multibody file loads as one entity owning one body per solid")
    func multibodyFileLoadsOneBodyPerSolid() async throws {
        let service = CADViewportService()
        _ = try await service.loadFile(from: try Self.fixtureURL(), id: "asm")

        #expect(service.modelBodies.count == 3, "one body per solid in the compound")
        let entity = try #require(service.entities["asm"])
        #expect(entity.bodyIDs.count == 3, "all three bodies belong to the one entity")
        #expect(Set(service.loadedShapes.keys) == ["asm"], "a multibody file is one entity")
    }

    /// The regression these tests exist for: framing must span the whole import.
    @MainActor
    @Test("Framing a multibody import spans every body, not just the first")
    func framingSpansTheWholeImport() async throws {
        let service = CADViewportService()
        _ = try await service.loadFile(from: try Self.fixtureURL(), id: "asm")

        let union = try #require(service.combinedBounds(ofEntities: ["asm"]))
        let entity = try #require(service.entities["asm"])
        let firstBodyID = try #require(entity.bodyIDs.first)
        let firstBodyBounds = try #require(service.bodyShapes[firstBodyID]?.bounds)

        // The discriminating pair. The first body is the 4mm box at the origin; the assembly runs
        // out to x = 63. A camera framing body 0 satisfies neither of these.
        #expect(
            union.max.x > 60,
            "the union must reach the far body at x = 57..63, not stop at the first body")
        #expect(
            (union.max.x - union.min.x) > 4 * (firstBodyBounds.max.x - firstBodyBounds.min.x),
            "the union must be far wider than the first body alone")

        // And it must be the true extent rather than merely wide: every body inside it.
        for bodyID in entity.bodyIDs {
            let b = try #require(service.bodyShapes[bodyID]?.bounds)
            #expect(b.min.x >= union.min.x && b.max.x <= union.max.x, "\(bodyID) outside the union")
        }
    }

    /// Every body of a multibody import carries its own durable identity, rather than the whole
    /// import sharing the first body's tables.
    @MainActor
    @Test("Each body of a multibody import resolves its own picks")
    func eachBodyResolvesItsOwnPicks() async throws {
        let service = CADViewportService()
        _ = try await service.loadFile(from: try Self.fixtureURL(), id: "asm")
        let entity = try #require(service.entities["asm"])

        var resolvedShapes: [OCCTSwift.Shape] = []
        for bodyID in entity.bodyIDs {
            let pick = try #require(
                service.resolveFacePick(bodyID: bodyID, triangleIndex: 0),
                "\(bodyID) must resolve a face pick of its own")
            #expect(pick.bodyID == bodyID, "the pick must name the body it was made on")
            resolvedShapes.append(pick.ref.shape)
        }

        // Distinct bodies must resolve to distinct geometry. Same-ordinal-different-body was a
        // real confusion in this stack, so compare the resolved faces rather than the ordinals.
        for (i, a) in resolvedShapes.enumerated() {
            for b in resolvedShapes[(i + 1)...] {
                #expect(
                    !a.isSame(as: b),
                    "two different bodies resolved triangle 0 to the same face")
            }
        }
    }
}
